spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/dns?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /dns

gmcc:
  hxs:
    dnsip: 192.168.1.2
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "%d - %msg%n"
  file: dns.log
